project:
  type: website

website:
  title: "lyndsayshand"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: pubs.qmd
        text: Publications
      - href: pbconsulting.qmd
        text: Pro Bono Consulting

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

