---
title: "Publications"
---

Wang, M., Harris, T., Shand, L. and Li, B. (2025), Changepoint Detection and Estimation for Spatial Functional Data - Detecting the Fingerprint of Mt. Pinatubo Eruption on Global Temperatures. *Submitted to Journal of American Statistical Association.*

Garrett, R, Shand, L. and Huerta J.G. (2025). A multivariate dynamic linear model for characterizing downstream impact of the Mt Pinatubo volcanic eruption. *In Revisions.* \url{https://doi.org/10.48550/arXiv.2408.13392}

Wheeler, L., B. Wagman, W. Smith, P. Davies, B. Cook, S. Brunell, A. Glen, D. Hackenburg, J. Lien, L. Shand, T. Zeitler (2025). Design and Simulation of a Logistically Constrained High Latitude, Low Altitude Stratospheric Aerosol Injection Scenario. *Environmental Research Letters.* Accepted Feb 2025.

Jun, S, L. Shand, and B. Li (2025). Tracing the impacts of Mount Pinatubo eruption on regional climate using spatially-varying changepoint detection. *Annals of Applied Statistics* (*Accepted for publication Oct 2024).* \url{https://doi.org/10.48550/arXiv.2409.08908}

Yarger, D., Wagman, B. M., Chowdhary, K., & Shand, L. (2024). Autocalibration of the E3SM version 2 atmosphere model using a PCA-based surrogate for spatial fields. Journal of Advances in Modeling Earth Systems, 16, e2023MS003961. https://doi.org/10.1029/2023MS003961

Wheeler L, Zeitler T, Brunell S, Lien J, Shand L, Wagman B, Martinez C and Potter K (2023) Performance assessment for climate intervention (PACI): preliminary application to a stratospheric aerosol injection scenario. *Front. Environ. Sci.* 11:1205515. doi: 10.3389/fenvs.2023.1205515

K. M. Larson, L. Shand, A. Staid, S. Gray, E. L. Roesler and D. Lyons (2022). "An Optical Flow Approach to Tracking Ship Track Behavior Using GOES-R Satellite Imagery," in *IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing*, vol. 15, pp. 6272-6282, 2022, doi: 10.1109/JSTARS.2022.3193024.

Patel, L. and L. Shand (2022). Toward data assimilation of ship-induced aerosol--cloud interactions. *Environmental Data Science, 1*, E31. doi:10.1017/eds.2022.21

J.D. Tucker, L. Shand, and K. Chowdhary (2021). Multimodal Bayesian Registration of Noisy Functions using Hamiltonian Monte Carlo. *Computational Statistics and Data Analysis*. DOI: 10.1016/j.csda.2021.107298

L. Patel, L. Shand, J.D. Tucker, and G. Huerta (2020). Assessing extreme value analysis to predict rare events from the global terrorism database. In JSM Proceedings, Section on Statistics in Defense and National Security. Alexandria, VA: American Statistical Association

Harris, T., Tucker J.D., B. Li, and L. Shand (2020). Elastic depths for detecting shape anomalies in functional data. *Technometrics*. doi: 10.1080/00401706.2020.1811156

Tucker, J. D., L. Shand, J. R. Lewis (2018). Handling Missing Data in self-exciting point process models. \*Spatial Statistics\*. 29.160-176.

Guo S., M. A. Cooper., and L. Shand (2018). A statistical representation of pyrotechnic research igniter output. \*AIP Conference Proceedings\*. 1979 (1). doi: 10.1063/1.5044973

Shand, L. and B. Li (2018). Spatially Varying Autoregressive Models for Prediction of New HIV Diagnoses. \*Journal of the Royal Statistical Society: Series C\*. https://doi.org/10.1111/rssc.12269

Shand, L. and B. Li (2017). Modeling Nonstationarity in Space and Time. \*Biometrics\*. https://doi.org/10.1111/biom.12656

Shand, L., W. M. Brown, L. F. Chaves, T. L. Goldberg, G. L. Hamer, L. Haramis, U. Kitron, E. D. Walker, and M.O. Ruiz (2016). Predicting West Nile Virus Infection Risk From the Synergistic Effects of Rainfall and Temperature. \*Journal of Medical Entomology\*. 1-10. doi: 10.1093/jme/tjw042.
